name: Make and deploy release

on:
  push:
    branches: [ "master" ]

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ format('yyyy.MM.dd', github.event.head_commit.timestamp) }}
          name: "${{ format('yyyy.MM.dd', github.event.head_commit.timestamp) }} (Work In Progress)"
          prerelease: true
          generate_release_notes: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
