name: Make and deploy release

on:
  push:
    branches: [ "master" ]

permissions:
  contents: write

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Environment
        id: vars
        run: |
          DATE="wip-$(date +'%Y-%m-%d')"
          echo "DATE=DATE" >> $GITHUB_ENV

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.DATE }}
          name: Work In Progress (${{ env.DATE }})
          prerelease: true
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
